DELETE FROM `Chambres` WHERE numeroChambre IS NOT NULL;
DELETE FROM `Lit` WHERE numeroLit IS NOT NULL;
DELETE FROM `Classes` WHERE idCLasse IS NOT NULL;
DELETE FROM `Etages` WHERE numeroEtage IS NOT NULL
